workspace:
  base: /go
  path: src/k8s.io/autoscaler

pipeline:
  build_vpa_admission_controller:
    image: registry.hub.docker.com/library/golang:1.11.1
    commands:
      - cd /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller/
      - go version
      - go get github.com/tools/godep
      - rm -f admission-controller
      - godep go build ./...
      - godep go build -o admission-controller

  test_vpa_admission_controller:
    image: registry.hub.docker.com/library/golang:1.11.1
    commands:
      - cd /go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller/
      - test -z "$$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -s -d {} + | tee /dev/stderr)"
      - test -z "$$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -s -w {} + | tee /dev/stderr)"
      - godep go test --test.short -race ./...

  push_vpa_admission_controller:
    image: plugins/docker
    repo: registry.usw.co/kubernetes-autoscaler/vpa-admission-controller
    tag: [ latest, "${DRONE_COMMIT_SHA}" ]
    context: ./vertical-pod-autoscaler/pkg/admission-controller
    dockerfile: ./vertical-pod-autoscaler/pkg/admission-controller/Dockerfile
    when:
      branch:
        - master
      event:
        - push
